import { PrismaClient, RepoVisibility, ShowInterestType, MediaType } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

/* ─── 假数据配置 ─── */

const USERS = [
  { phone: '13800000001', nickname: '摇滚小王', password: 'demo123456' },
  { phone: '13800000002', nickname: '独立莉莉', password: 'demo123456' },
  { phone: '13800000003', nickname: '鼓手阿强', password: 'demo123456' },
  { phone: '13800000004', nickname: '现场狂人', password: 'demo123456' },
  { phone: '13800000005', nickname: '乐评人老张', password: 'demo123456' },
];

const SHOWS = [
  { artistName: '痛仰乐队', venueName: 'MAO Livehouse', showDate: new Date('2026-06-15T20:00:00+08:00'), city: '北京', description: '痛仰「在路上」全国巡演北京站' },
  { artistName: '万能青年旅店', venueName: '疆进酒', showDate: new Date('2026-05-20T20:30:00+08:00'), city: '北京', description: '万能青年旅店「冀西南林路行」专场' },
  { artistName: '九连真人', venueName: '育音堂音乐公园', showDate: new Date('2026-06-03T20:00:00+08:00'), city: '上海', description: '九连真人「六连」新专辑巡演' },
  { artistName: '新裤子', venueName: '凯迪拉克中心', showDate: new Date('2026-07-10T19:30:00+08:00'), city: '北京', description: '新裤子「最后的乐队」巡回演唱会' },
  { artistName: '刺猬', venueName: 'VOX Livehouse', showDate: new Date('2026-08-05T20:00:00+08:00'), city: '武汉', description: '刺猬「赤子白仙」夏季巡演' },
  { artistName: '草东没有派对', venueName: 'NU Space', showDate: new Date('2026-04-15T20:00:00+08:00'), city: '成都', description: '草东没有派对「瓦合」巡演成都站' },
  { artistName: '海朋森', venueName: 'ModernSky LAB', showDate: new Date('2026-06-28T20:30:00+08:00'), city: '上海', description: '海朋森「成長小說」专辑巡演' },
];

/* ─── Placeholder images (picsum.photos ensures real-looking photos) ─── */
// Using seed params to get consistent, music/concert-appropriate images
// Local SVG placeholders (generated by generate-placeholders.js)
const LOCAL_PLACEHOLDERS = (() => {
  const urls: string[] = [];
  // Show covers (0-6)
  for (let i = 1; i <= 7; i++) urls.push(`/uploads/placeholder-show-${i}.svg`);
  // Scene images (7-31)
  for (let i = 1; i <= 25; i++) urls.push(`/uploads/placeholder-scene-${i}.svg`);
  // Extra venue images (32-43)
  for (let i = 1; i <= 12; i++) urls.push(`/uploads/placeholder-extra-${i}.svg`);
  return urls;
})();

const IMAGES: { url: string; type: MediaType }[] = LOCAL_PLACEHOLDERS.map((url) => ({ url, type: MediaType.IMAGE }));

/* ─── Repo templates ─── */
const REPOS_DATA = [
  // 痛仰 @ MAO (showIndex 0)
  { userIdx: 0, template: 'C', hook: '我在这场演出开到了人生中最长的一趟火车', body: '全场从第一首就开始躁。高虎喊了一句"准备好了吗"，然后就没有然后了——直接被 pogo 大军卷走。最后一首《西湖》全场大合唱，嗓子都喊哑了。', vibe: [5, 4, 5], images: [0, 1], tags: [['pogo', 'chorus'], ['light-show']] },
  { userIdx: 1, template: 'A', hook: '吉他的第一个音响起的那一刻，我鸡皮疙瘩全起来了', body: '痛仰的现场真的不需要任何形容词。失真一出来，鸡皮疙瘩就起来了。音响调得特别好，人声清晰，低音下潜到位。', vibe: [4, 5, 4], images: [2], tags: [['guitar-solo']] },
  { userIdx: 2, template: 'B', hook: '这场演出像一记重拳打在胸口', body: '作为鼓手，特别关注了大伟的编鼓。今天的 hi-hat 开镲节奏偏快，整体 tempo 比专辑版激进，但完全在掌控中。最后一首歌的军鼓滚奏绝了。', vibe: [5, 3, 5], images: [3], tags: [['drum-explosion', 'light-show']] },
  { userIdx: 4, template: 'D', hook: '比想象中好，但还有进步空间', body: '整体完成度不错，但暖场太长。高虎今天状态还可以，但有几处 vocal 有点飘。音响在中高频段有点炸，低频还行。MAO 这个场地也就这样了。', vibe: [3, 3, 4], images: [14], tags: [['venue-panorama']] },

  // 万能青年旅店 @ 疆进酒 (showIndex 1) - 已过去
  { userIdx: 0, template: 'A', hook: '小号声响起的那一刻，全场都静止了', body: '《杀死那个石家庄人》的小号前奏一出来，全场安静了三秒，然后就是雷鸣般的掌声。姬赓的贝斯线在现场听比专辑里厚重太多了。', vibe: [5, 5, 5], images: [4, 5], tags: [['vocal-scream', 'guitar-solo'], ['chorus']] },
  { userIdx: 1, template: 'B', hook: '这场演出像一场漫长而温柔的告别', body: '万青的现场像一场修行。没有过多的互动，没有花哨的舞台效果，就是纯粹的音乐轰炸。《采石》的器乐部分简直是耳朵的盛宴。', vibe: [5, 4, 4], images: [6], tags: [['bass-groove']] },
  { userIdx: 3, template: 'C', hook: '我在这场演出站了三个小时一动不动', body: '站桩式看完了整场，不是不想动，是动不了——被音乐钉住了。首次听《冀西南林路行》全专 live，编排比专辑更有冲击力。', vibe: [4, 4, 3], images: [15], tags: [['venue-panorama']] },

  // 九连真人 @ 育音堂 (showIndex 2) - 已过去
  { userIdx: 2, template: 'C', hook: '我在这场演出被人群挤到了舞台第三排', body: '九连的现场太野了。客家话一出来，全场都在跟着喊"莫欺少年穷"。育音堂这个场地小，能量密度极高，差点 crowd surfing。', vibe: [4, 3, 5], images: [7], tags: [['circle-pit', 'vocal-scream']] },
  { userIdx: 3, template: 'A', hook: '阿龙唢呐响起来的那一刻，我炸了', body: '没想到九连真人的现场这么炸。唢呐 solo 的时候全场都疯了。音响在小场地算不错的，就是有点糊。氛围满分。', vibe: [4, 3, 5], images: [8], tags: [['metal-horn', 'stage-dive']] },
  { userIdx: 4, template: 'D', hook: '客家话摇滚，有点意思但还需要沉淀', body: '九连的能量是真的强，但编曲上有些段落略显重复。阿龙的 vocal 表现力很强，唢呐是亮点。期待他们之后的作品。', vibe: [3, 3, 4], images: [16], tags: [['merch']] },

  // 新裤子 @ 凯迪拉克 (showIndex 3) - 即将
  { userIdx: 1, template: 'A', hook: '彭磊开口的那一刻，我眼泪差点下来', body: '《没有理想的人不伤心》前奏一响，全场都在跟唱。大场馆的好处是视觉效果拉满，但少了 livehouse 那种亲密感。', vibe: [4, 5, 4], images: [9, 10], tags: [['light-show', 'chorus'], ['venue-panorama']] },

  // 草东没有派对 @ NU Space (showIndex 5) - 已过去
  { userIdx: 3, template: 'B', hook: '这场演出像一盆冷水浇在头上', body: '草东的丧是真诚的丧。整个演出从《丑奴儿》到《瓦合》，情绪层层递进。NU Space 的音响很好，小场地就是不一样。', vibe: [5, 5, 4], images: [11], tags: [['guitar-solo', 'chorus']] },
  { userIdx: 0, template: 'A', hook: '《山海》副歌爆发的那一刻，我脑子一片空白', body: '前排 survival mode。草东的鼓手真的太猛了，双踩一出来地板都在震。凡凡的 vocal 比专辑里还稳，《但》那首直接听哭了。', vibe: [5, 4, 5], images: [12], tags: [['drum-explosion', 'crowd-surfing']] },
  { userIdx: 1, template: 'C', hook: '我在这场演出把隐形眼镜哭掉了', body: '不是开玩笑的。从《烂泥》到《缸》，每一首都在戳。散场后和朋友在门口坐了半小时，一句话都说不出来。', vibe: [5, 4, 5], images: [17], tags: [['ticket']] },

  // 海朋森 @ ModernSky (showIndex 6) - 即将
  { userIdx: 1, template: 'B', hook: '这场演出像一部摇滚歌剧', body: '海朋森的现场叙事性很强，陈思江的舞台表现力让人移不开眼。ModernSky 的设备和调音都一流，期待值拉满。', vibe: [4, 5, 4], images: [13], tags: [['vocal-scream', 'light-show']] },

  // 刺猬 @ VOX (showIndex 4) - 即将
  { userIdx: 0, template: 'A', hook: '子健开口的那一刻，我确信青春还没结束', body: '刺猬的现场就是青春本身。子健的破音和石璐的鼓声交织在一起，噪音里全是真诚。期待八月武汉场！', vibe: [4, 4, 5], images: [18, 19], tags: [['guitar-solo', 'chorus'], ['venue-panorama']] },
];

/* ─── Comment data ─── */
const COMMENTS_DATA: { repoIdx: number; userIdx: number; body: string; replies?: { userIdx: number; body: string }[] }[] = [
  { repoIdx: 0, userIdx: 1, body: '同场！当时我就站你旁边，那趟火车我也在开 🚂', replies: [{ userIdx: 0, body: '哈哈那下次一起冲前排！' }] },
  { repoIdx: 0, userIdx: 2, body: '大伟今天真的猛，鼓点每一步都踩在心跳上', replies: [{ userIdx: 2, body: '尤其是最后那首的军鼓滚奏，回来我练了两天没练会' }] },
  { repoIdx: 1, userIdx: 4, body: '音响真的可以，比上次在MAO好多了', replies: [] },
  { repoIdx: 5, userIdx: 0, body: '草东的鼓真的牛逼，分享歌单吗兄弟！', replies: [{ userIdx: 3, body: '私信你了，加个好友以后一起冲现场' }] },
  { repoIdx: 5, userIdx: 4, body: '刚看完草东回来，跟你感受一样', replies: [] },
  { repoIdx: 10, userIdx: 3, body: '同哭。那晚成都下了小雨，和心情很配。', replies: [{ userIdx: 1, body: '对，出来发现下雨了，感觉整个世界都在配合那场演出' }, { userIdx: 3, body: '「烂泥」现场版真的绝了' }] },
  { repoIdx: 2, userIdx: 4, body: '最后的小号声绝了', replies: [] },
];

/* ─── Main ─── */
async function main() {
  console.log('🧹 清理旧数据...');
  await prisma.match.deleteMany();
  await prisma.memoryHookLike.deleteMany();
  await prisma.repoLike.deleteMany();
  await prisma.comment.deleteMany();
  await prisma.repoMedia.deleteMany();
  await prisma.repo.deleteMany();
  await prisma.showInterest.deleteMany();
  await prisma.show.deleteMany();
  await prisma.userBlock.deleteMany();
  await prisma.report.deleteMany();
  await prisma.user.deleteMany();

  console.log('👤 创建用户...');
  const passwordHash = await bcrypt.hash('demo123456', 10);
  const users = [];
  for (const u of USERS) {
    const user = await prisma.user.create({
      data: { phone: u.phone, passwordHash, nickname: u.nickname },
    });
    users.push(user);
  }

  console.log('🎵 创建演出条目...');
  const shows = [];
  for (const s of SHOWS) {
    const show = await prisma.show.create({
      data: {
        artistName: s.artistName,
        venueName: s.venueName,
        showDate: s.showDate,
        city: s.city,
        description: s.description,
      },
    });
    shows.push(show);
  }

  // Track show→user attendance for matching later
  const attendedShows: { showIdx: number; userIdx: number }[] = [
    { showIdx: 0, userIdx: 0 }, { showIdx: 0, userIdx: 1 }, { showIdx: 0, userIdx: 2 }, { showIdx: 0, userIdx: 4 },
    { showIdx: 1, userIdx: 0 }, { showIdx: 1, userIdx: 1 }, { showIdx: 1, userIdx: 3 },
    { showIdx: 2, userIdx: 2 }, { showIdx: 2, userIdx: 3 }, { showIdx: 2, userIdx: 4 },
    { showIdx: 5, userIdx: 0 }, { showIdx: 5, userIdx: 1 }, { showIdx: 5, userIdx: 3 },
  ];
  const wantedShows: { showIdx: number; userIdx: number }[] = [
    { showIdx: 3, userIdx: 0 }, { showIdx: 3, userIdx: 1 }, { showIdx: 3, userIdx: 2 }, { showIdx: 3, userIdx: 4 },
    { showIdx: 4, userIdx: 0 }, { showIdx: 4, userIdx: 3 },
    { showIdx: 6, userIdx: 1 }, { showIdx: 6, userIdx: 2 },
  // 痛仰 showIdx 0 — 让更多人造访
  { showIdx: 0, userIdx: 3 },
  ];

  console.log('📝 创建兴趣标记...');
  for (const a of attendedShows) {
    await prisma.showInterest.create({
      data: { userId: users[a.userIdx].id, showId: shows[a.showIdx].id, type: ShowInterestType.ATTENDED },
    });
  }
  for (const w of wantedShows) {
    await prisma.showInterest.create({
      data: { userId: users[w.userIdx].id, showId: shows[w.showIdx].id, type: ShowInterestType.WANT_TO_SEE },
    });
  }

  console.log('📝 创建 Repos + 媒体...');
  const repos: { id: string; userId: string; showIdx: number }[] = [];
  for (const r of REPOS_DATA) {
    const showIdx = r.images.length > 0 ? Math.floor(r.images[0] / 2) % SHOWS.length : 0;
    // Map to actual show index based on order
    const showIdxMap = [0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 5, 5, 5, 6];
    const actualShowIdx = showIdxMap[repos.length] ?? 0;

    const repo = await prisma.repo.create({
      data: {
        userId: users[r.userIdx].id,
        showId: shows[actualShowIdx].id,
        body: r.body,
        memoryHook: r.hook,
        memoryTemplate: r.template,
        vibeBand: r.vibe[0],
        vibeSound: r.vibe[1],
        vibeAtmosphere: r.vibe[2],
        visibility: RepoVisibility.PUBLIC,
        media: {
          create: r.images.map((imgIdx, i) => ({
            url: IMAGES[imgIdx].url,
            type: IMAGES[imgIdx].type,
            sortOrder: i,
            tags: r.tags[i]?.length ? JSON.stringify(r.tags[i]) : '[]',
          })),
        },
      },
    });
    repos.push({ id: repo.id, userId: users[r.userIdx].id, showIdx: actualShowIdx });
  }

  console.log('💬 创建评论（含回复）...');
  for (const c of COMMENTS_DATA) {
    const repoId = repos[c.repoIdx]?.id;
    if (!repoId) continue;

    const comment = await prisma.comment.create({
      data: {
        repoId,
        userId: users[c.userIdx].id,
        body: c.body,
        parentId: null,
      },
    });
    await prisma.repo.update({ where: { id: repoId }, data: { commentCount: { increment: 1 } } });

    if (c.replies) {
      for (const reply of c.replies) {
        await prisma.comment.create({
          data: {
            repoId,
            userId: users[reply.userIdx].id,
            body: reply.body,
            parentId: comment.id,
          },
        });
        await prisma.repo.update({ where: { id: repoId }, data: { commentCount: { increment: 1 } } });
      }
    }
  }

  console.log('❤️ 创建点赞...');
  const likes = [
    { repoIdx: 0, userIdx: 1 }, { repoIdx: 0, userIdx: 2 }, { repoIdx: 0, userIdx: 3 },
    { repoIdx: 1, userIdx: 2 }, { repoIdx: 1, userIdx: 4 },
    { repoIdx: 4, userIdx: 1 }, { repoIdx: 4, userIdx: 2 }, { repoIdx: 4, userIdx: 3 }, { repoIdx: 4, userIdx: 4 },
    { repoIdx: 5, userIdx: 0 }, { repoIdx: 5, userIdx: 3 },
    { repoIdx: 10, userIdx: 0 }, { repoIdx: 10, userIdx: 3 },
    { repoIdx: 11, userIdx: 1 }, { repoIdx: 11, userIdx: 2 },
    // 九连 (确保有赞以生成封面)
    { repoIdx: 7, userIdx: 1 }, { repoIdx: 7, userIdx: 4 },
    // 刺猬 (确保有赞以生成封面)
    { repoIdx: 15, userIdx: 1 }, { repoIdx: 15, userIdx: 2 }, { repoIdx: 15, userIdx: 3 },
  ];
  for (const l of likes) {
    const repo = repos[l.repoIdx];
    if (!repo) continue;
    const existing = await prisma.repoLike.findUnique({
      where: { userId_repoId: { userId: users[l.userIdx].id, repoId: repo.id } },
    });
    if (!existing) {
      await prisma.repoLike.create({ data: { userId: users[l.userIdx].id, repoId: repo.id } });
      await prisma.repo.update({ where: { id: repo.id }, data: { likeCount: { increment: 1 } } });
    }
  }

  // Memory hook likes
  const memLikes = [
    { repoIdx: 0, userIdx: 1 }, { repoIdx: 0, userIdx: 3 },
    { repoIdx: 4, userIdx: 2 }, { repoIdx: 4, userIdx: 3 },
    { repoIdx: 5, userIdx: 0 },
    { repoIdx: 10, userIdx: 3 },
  ];
  for (const l of memLikes) {
    const repo = repos[l.repoIdx];
    if (!repo) continue;
    const existing = await prisma.memoryHookLike.findUnique({
      where: { userId_repoId: { userId: users[l.userIdx].id, repoId: repo.id } },
    });
    if (!existing) {
      await prisma.memoryHookLike.create({ data: { userId: users[l.userIdx].id, repoId: repo.id } });
      await prisma.repo.update({ where: { id: repo.id }, data: { memoryHookLikeCount: { increment: 1 } } });
    }
  }

  // Trigger matching by calling the internal service (skip for seed simplicity)
  // Matches will be created when users interact through the app

  console.log('');
  console.log('✅ 种子数据创建完成！');
  console.log('────────────────────────────');
  console.log('📱 测试账号（密码统一：demo123456）');
  for (const u of USERS) {
    console.log(`   ${u.phone} → ${u.nickname}`);
  }
  console.log(`🎵 共创建 ${shows.length} 场演出`);
  console.log(`📝 共创建 ${repos.length} 条记录`);
  console.log(`💬 共创建 ${COMMENTS_DATA.reduce((s, c) => s + 1 + (c.replies?.length ?? 0), 0)} 条评论`);
  console.log(`❤️  共创建 ${likes.length} 个点赞 + ${memLikes.length} 个记忆赞`);
  console.log(`📷 包含 ${IMAGES.length} 张本地占位图片`);
  console.log('────────────────────────────');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
